config/routes.rb
Rails.application.routes.draw do
  resources :timeline_events
  get 'written_works/new'

  get 'saints/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'saints#map'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/signup',        to: 'users#new'
  post   '/signup',        to: 'users#create'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/map',           to: 'saints#map'
  get    '/pending_users', to: 'users#pending_users'
  
  resources :users do
    member do
      get 'approve_account'
      get 'deactivate_user'
      get 'reactivate_user'
      get 'promote_to_admin'
      get 'demote_to_user'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:     [:new, :create, :edit, :update]
  resources :saints do
    member do
      get :following, :followers
    end
  end
  resources :relationships
  resources :written_works
  resources :saint_photos
end

app/models/written_work.rb
class WrittenWork < ApplicationRecord
  belongs_to :saint
  validates :saint_id, presence: true
  validates :title, presence: true, length: { maximum: 300 }
  validates :publication_date, presence: true
  validates :publication_accuracy, presence: true
end

app/controllers/written_works_controller.rb
class WrittenWorksController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
  before_action :admin_user,     only: [:create, :destroy]

  def index
    @written_works = WrittenWork.all
  end

  def show
    @written_work = WrittenWork.find(params[:id])
  end

  def new
    @written_work = WrittenWork.new
  end

  def edit
    @written_work = WrittenWork.find(params[:id])
  end

	def create
    current_saint = Saint.find(params[:current_saint_id])
    current_saint.written_works.create(title: params[:title], publication_date: params[:publication_date],
    																	 publication_accuracy: params[:publication_accuracy],
    																	 description: params[:description])
    redirect_to current_saint
  end

  def update
    @written_work = WrittenWork.find(params[:id])
    respond_to do |format|
      if @written_work.update(written_work_params)
        format.html { redirect_to @written_work, notice: 'Written work was successfully updated.' }
        format.json { render :show, status: :ok, location: @written_work }
      else
        format.html { render :edit }
        format.json { render json: @written_work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	WrittenWork.find(params[:id]).destroy
    flash[:success] = "Written work deleted"
    redirect_to saints_url
  end

  private

  def written_work_params
    params.require(:written_work).permit(:title, :publication_date, :description,
      :publication_accuracy)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/written_works_helper.rb
module WrittenWorksHelper
end

app/views/written_works/_form.html.erb
<%= simple_form_for(@written_work) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :publication_date %>
    <%= f.input :description %>
    <%= f.input :publication_accuracy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/written_works/edit.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <h1>Editing Written Work</h1>
  
  <%= render 'form', written_work: @written_work %>
  
  <%= link_to 'Show', @written_work %> |
  <%= link_to 'Back', written_works_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/written_works/index.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <p id="notice"><%= notice %></p>
  <%= render 'shared/menu_toggle' %>

  <h1>Written Works</h1>
  
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Publication Date</th>
        <th>Description</th>
        <th>Publication Accuracy</th>
        <th>Event description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @written_works.each do |written_work| %>
        <tr>
          <td><%= written_work.title %></td>
          <td><%= written_work.publication_date %></td>
          <td><%= written_work.description %></td>
          <td><%= written_work.publication_accuracy %></td>
          <td><%= link_to 'Show', written_work %></td>
          <td><%= link_to 'Edit', edit_written_work_path(written_work) %></td>
          <td><%= link_to 'Destroy', written_work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Written Work', new_written_work_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/written_works/new.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <h1>New Written Work</h1>

  <%= render 'form', written_work: @written_work %>

  <%= link_to 'Back', written_works_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/written_works/show.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <p>
    <strong>Saint:</strong>
    <%= link_to @written_work.saint.name, @written_work.saint %>
  </p>
  
  <p>
    <strong>Title:</strong>
    <%= @written_work.title %>
  </p>
  
  <p>
    <strong>Publication Date:</strong>
    <%= @written_work.publication_date %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= @written_work.description %>
  </p>
  
  <p>
    <strong>Publication Accuracy:</strong>
    <%= @written_work.publication_accuracy %>
  </p>
  
  <%= link_to 'Edit', edit_written_work_path(@written_work) %> |
  <%= link_to 'Back', written_works_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>