config/routes.rb
Rails.application.routes.draw do
  resources :timeline_events
  get 'written_works/new'

  get 'saints/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'saints#map'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/signup',        to: 'users#new'
  post   '/signup',        to: 'users#create'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/map',           to: 'saints#map'
  get    '/pending_users', to: 'users#pending_users'
  
  resources :users do
    member do
      get 'approve_account'
      get 'deactivate_user'
      get 'reactivate_user'
      get 'promote_to_admin'
      get 'demote_to_user'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:     [:new, :create, :edit, :update]
  resources :saints do
    member do
      get :following, :followers
    end
  end
  resources :relationships
  resources :written_works
  resources :saint_photos
end

app/models/saint.rb
class Saint < ApplicationRecord
  APPROX_YEAR = 0
  EXACT_YEAR = 1
  EXACT_MONTH_YEAR = 2
  EXACT_DATE = 3
  YEAR_FORMAT = "%-Y"
  MONTH_YEAR_FORMAT = "%B %-Y"
  MONTH_DAY_YEAR_FORMAT = "%B %d, %-Y"
  DATE_ACCURACIES = {
    'We only know the approximate year.' => APPROX_YEAR,
    'We only know the exact year.' => EXACT_YEAR,
    'We only know the exact month and year.' => EXACT_MONTH_YEAR,
    'We know the exact day, month, and year.' => EXACT_DATE
    }.freeze
  enum birth_accuracy: DATE_ACCURACIES, _prefix: true
  enum death_accuracy: DATE_ACCURACIES, _prefix: true
  enum beatification_accuracy: DATE_ACCURACIES, _prefix: true
  enum canonization_accuracy: DATE_ACCURACIES, _prefix: true
  enum title: { 'Saint' => 0,
                'Blessed' => 1,
                'Venerable' => 2,
                'Servant of God' => 3 }
  mount_uploader :avatar, AvatarUploader
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :written_works, dependent: :destroy
  has_many :timeline_events, dependent: :destroy
  has_many :saint_photos, dependent: :destroy
  validates :name,
    presence: { message: 'name required' },
    length: { maximum: 255, message: 'must be 255 characters or less' }
  validates :gender, presence: { message: 'gender required' }
  validates :feast_day, presence: { message: 'feast day required' }
  validates :birth_accuracy, inclusion: { in: birth_accuracies.keys },
                             presence: { message: 'birth accuracy required' }
  validates :death_accuracy, inclusion: { in: death_accuracies.keys },
                             presence: { message: 'death accuracy required' }
  validates :birth_location,
    length: { maximum: 255, message: 'must be 255 characters or less' }
  validates :death_location,
    length: { maximum: 255, message: 'must be 255 characters or less' }
  # validates :beatification_accuracy, inclusion: { in: beatification_accuracies.keys }
  # validates :canonization_accuracy, inclusion: { in: canonization_accuracies.keys }
  #
  validates :short_description, presence: { message: 'short description required' }
  validates :long_description, presence: { message: 'long description required' }
  validates :title, inclusion: { in: titles.keys },
                                 presence: { message: 'title required' }
  validates :fame_level, presence: { message: 'fame level required' }

  # Follows a saint.
  def follow(other_saint)
    following << other_saint
  end

  # Unfollows a saint.
  def unfollow(other_saint)
    following.delete(other_saint)
  end

  # Returns true if the current saint is following the other saint.
  def following?(other_saint)
    following.include?(other_saint)
  end
  
  def has_feast_day?
    feast_day.present?
  end

  def show_feast_day
    feast_day.strftime("%B %d")
  end

  def has_birthday?
    birth_date.present?
  end

  def has_birth_location?
    birth_location.present?
  end

  def has_deathday?
    death_date.present?
  end

  def has_death_location?
    death_location.present?
  end

  def has_beatification_date?
    beatification_date.present?
  end

  def has_canonization_date?
    canonization_date.present?
  end

  def accurate_saint_date(date_type)
    saint_date = birth_date
    date_accuracy = 0
    case date_type
    when 'birth'
      saint_date = birth_date
      date_accuracy = birth_accuracy
    when 'death'
      saint_date = death_date
      date_accuracy = death_accuracy
    when 'beatification'
      saint_date = beatification_date
      date_accuracy = beatification_accuracy
    when 'canonization'
      saint_date = canonization_date
      date_accuracy = canonization_accuracy
    end
    apply_accuracy(saint_date, date_accuracy)
  end

  private

  def apply_accuracy(saint_date, date_accuracy)
    case date_accuracy
    when DATE_ACCURACIES.key(APPROX_YEAR)
      'c. ' + saint_date.strftime(YEAR_FORMAT)
    when DATE_ACCURACIES.key(EXACT_YEAR)
      saint_date.strftime(YEAR_FORMAT)
    when DATE_ACCURACIES.key(EXACT_MONTH_YEAR)
      saint_date.strftime(MONTH_YEAR_FORMAT)
    when DATE_ACCURACIES.key(EXACT_DATE)
      saint_date.strftime(MONTH_DAY_YEAR_FORMAT)
    end
  end
end

app/controllers/saints_controller.rb
class SaintsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def index
    prepare_meta_tags title: "Saints List", description: "Explore the Catholic Church's entire list of saints."

    @all_saints = Saint.all
    if current_user
      @saints = @all_saints
    else
      @saints = @all_saints.where(published: true)
    end
  end

  def show
    @saint = Saint.friendly.find(params[:id])
    # Redirect to the latest slug.
    if request.path != saint_path(@saint)
      redirect_to @saint, status: :moved_permanently
    end

    if @saint.published || current_user
      @accurate_birth_date = @saint.accurate_saint_date('birth')
      @accurate_death_date = @saint.accurate_saint_date('death')
      @accurate_beatification_date = @saint.accurate_saint_date('beatification')
      @accurate_canonization_date = @saint.accurate_saint_date('canonization')
      @following_saints = @saint.following
      @follower_saints = @saint.followers
      @written_works = @saint.written_works.order(publication_date: :asc)
      @timeline_events = @saint.timeline_events.order(event_priority: :asc)
      @saint_photos = @saint.saint_photos.order(photo_priority: :asc)

      prepare_meta_tags(title: @saint.name,
                        description: @saint.short_description,
                        keywords: @saint.name)
    else
      redirect_to saints_url
    end
  end

  def new
    @saint = Saint.new
  end

  def create
    @saint = Saint.new(saint_params)
    if @saint.save
      flash[:info] = 'Saint has been successfully created.'
      redirect_to saints_url
    else
      render 'new'
    end
  end

  def edit
    @saint = Saint.friendly.find(params[:id])
  end

  def update
    @saint = Saint.friendly.find(params[:id])
    if @saint.update_attributes(saint_params)
      flash[:success] = 'Saint updated'
      redirect_to @saint
    else
      render 'edit'
    end
  end

  def destroy
    Saint.find(params[:id]).destroy
    flash[:success] = 'Saint deleted'
    redirect_to saints_url
  end

  def map
    prepare_meta_tags title: "Saint Map", description: "Explore the Catholic Church's entire map of saints."

    @all_saints = Saint.all
    @saints = @all_saints.where(published: true)
    @popes = @saints.where(pope: true)
    @cardinals = @saints.where(cardinal: true)
    @bishops = @saints.where(bishop: true)
    @priests = @saints.where(priest: true)
    @religious = @saints.where(religious: true)
    @laypeople = @saints.where(lay: true)
    @martyrs = @saints.where(martyr: true)
    @founders = @saints.where(founder: true)
    @mystics = @saints.where(mystic: true)
    @royalty = @saints.where(royalty: true)
    @doctors_of_the_church = @saints.where(doctor_of_the_church: true)
    @early_church_fathers = @saints.where(early_church_father: true)

    @birth_hash = build_birth_markers(@saints)
    @death_hash = build_death_markers(@saints)
    @pope_birth_hash = build_birth_markers(@popes)
    @pope_death_hash = build_death_markers(@popes)
    @cardinal_birth_hash = build_birth_markers(@cardinals)
    @cardinal_death_hash = build_death_markers(@cardinals)
    @bishop_birth_hash = build_birth_markers(@bishops)
    @bishop_death_hash = build_death_markers(@bishops)
    @priest_birth_hash = build_birth_markers(@priests)
    @priest_death_hash = build_death_markers(@priests)
    @religious_birth_hash = build_birth_markers(@religious)
    @religious_death_hash = build_death_markers(@religious)
    @layperson_birth_hash = build_birth_markers(@laypeople)
    @layperson_death_hash = build_death_markers(@laypeople)
    @martyr_birth_hash = build_birth_markers(@martyrs)
    @martyr_death_hash = build_death_markers(@martyrs)
    @founder_birth_hash = build_birth_markers(@founders)
    @founder_death_hash = build_death_markers(@founders)
    @mystic_birth_hash = build_birth_markers(@mystics)
    @mystic_death_hash = build_death_markers(@mystics)
    @royalty_birth_hash = build_birth_markers(@royalty)
    @royalty_death_hash = build_death_markers(@royalty)
    @doctor_of_the_church_birth_hash = build_birth_markers(@doctors_of_the_church)
    @doctor_of_the_church_death_hash = build_death_markers(@doctors_of_the_church)
    @early_church_father_birth_hash = build_birth_markers(@early_church_fathers)
    @early_church_father_death_hash = build_death_markers(@early_church_fathers)

    gon.birth_hash = @birth_hash
    gon.death_hash = @death_hash
    gon.pope_birth_hash = @pope_birth_hash
    gon.pope_death_hash = @pope_death_hash
    gon.cardinal_birth_hash = @cardinal_birth_hash
    gon.cardinal_death_hash = @cardinal_death_hash
    gon.bishop_birth_hash = @bishop_birth_hash
    gon.bishop_death_hash = @bishop_death_hash
    gon.priest_birth_hash = @priest_birth_hash
    gon.priest_death_hash = @priest_death_hash
    gon.religious_birth_hash = @religious_birth_hash
    gon.religious_death_hash = @religious_death_hash
    gon.layperson_birth_hash = @layperson_birth_hash
    gon.layperson_death_hash = @layperson_death_hash
    gon.martyr_birth_hash = @martyr_birth_hash
    gon.martyr_death_hash = @martyr_death_hash
    gon.founder_birth_hash = @founder_birth_hash
    gon.founder_death_hash = @founder_death_hash
    gon.mystic_birth_hash = @mystic_birth_hash
    gon.mystic_death_hash = @mystic_death_hash
    gon.royalty_birth_hash = @royalty_birth_hash
    gon.royalty_death_hash = @royalty_death_hash
    gon.doctor_of_the_church_birth_hash = @doctor_of_the_church_birth_hash
    gon.doctor_of_the_church_death_hash = @doctor_of_the_church_death_hash
    gon.early_church_father_birth_hash = @early_church_father_birth_hash
    gon.early_church_father_death_hash = @early_church_father_death_hash
  end

  private

  def saint_params
    params.require(:saint).permit(:name, :gender, :feast_day,
      :birth_date, :birth_accuracy, :death_date, :death_accuracy,
      :birth_location, :death_location, :beatification_date,
      :canonization_date, :birth_latitude, :birth_longitude,
      :death_latitude, :death_longitude, :pope, :cardinal, :bishop,
      :priest, :religious, :lay, :martyr, :founder, :mystic, :royalty,
      :doctor_of_the_church, :early_church_father, :avatar,
      :avatar_caption, :avatar_description, :avatar_alternative_text,
      :beatification_accuracy, :canonization_accuracy,
      :short_description, :long_description, :title,
      :fame_level, :published)
  end

  def build_birth_markers(saints)
    saints_birth_hash = Gmaps4rails.build_markers(saints) do |saint, marker|
      marker.lat saint.birth_latitude
      marker.lng saint.birth_longitude
      marker.infowindow render_to_string(:partial => "/saints/saint_infowindow", :locals => { :saint => saint })
      marker.title "#{saint.name}"
    end
    return saints_birth_hash
  end

  def build_death_markers(saints)
    saints_death_hash = Gmaps4rails.build_markers(saints) do |saint, marker|
      marker.lat saint.death_latitude
      marker.lng saint.death_longitude
      # marker.infowindow "<h4>#{saint.name}</h4><br><b>Born:</b> #{saint.birth_date.strftime("%B %d, %Y")} #{saint.birth_location}<br> <img src='http://www.totus2us.com/typo3temp/pics/feaf790989.jpg' style='width: 50%; height: 50%' />"
      marker.infowindow render_to_string(:partial => "/saints/saint_infowindow", :locals => { :saint => saint })
      marker.title "#{saint.name}"
    end
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/saints_helper.rb
module SaintsHelper
end

app/views/saints/_admin_modal.html.erb
<div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="adminModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="adminModalLabel">
          Admin Controls
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- /.modal-header -->
      <div class="modal-body">
        <%= render 'saints/admin_saint_controls' %>
      </div>
      <!-- /.modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
      <!-- /.modal-footer -->
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal fade -->

app/views/saints/_admin_saint_controls.html.erb
<h1>
  <%= link_to "Edit Saint", edit_saint_path(@saint) %>
</h1>
<div id="accordion" role="tablist">
  <div class="card">
    <div class="card-header" role="tab" id="timelineEvent">
      <h5 class="mb-0">
        <a data-toggle="collapse" href="#collapseTimelineEvent" aria-expanded="true" aria-controls="collapseTimelineEvent">
          Create Timeline Event
        </a>
      </h5>
      <!-- /.mb-0 -->
    </div>
    <!-- /.card-header -->
    <div id="collapseTimelineEvent" class="collapse" role="tabpanel" aria-labelledby="timelineEvent" data-parent="#accordion">
      <div class="card-body">
        <%= form_for(@saint.timeline_events.build) do |f| %>
          <div><%= hidden_field_tag :current_saint_id, @saint.id %></div>
          <%= label_tag(:event_priority, "Event Priority Level (Required)") %>
          <%= text_field_tag(:event_priority) %>
          <%= label_tag(:event_title, "Event Title (Required)") %>
          <%= text_field_tag(:event_title) %>
          <%= label_tag(:event_time, "Event Time (Required)") %>
          <%= text_field_tag(:event_time) %>
          <%= label_tag(:event_description, "Write the event's description") %>
          <%= text_field_tag(:event_description) %>
          <%= label_tag(:image, "Upload Image") %>
          <%= f.file_field :image %>
          <%= label_tag(:image_caption, "Write an Image Caption") %>
          <%= text_field_tag(:image_caption) %>
          <%= label_tag(:image_description, "Write an Image Description") %>
          <%= text_field_tag(:image_description) %>
          <%= label_tag(:image_alternative_text, "Write the alternative text for the image") %>
          <%= text_field_tag(:image_alternative_text) %>
          <%= f.submit "Create Timeline Event", class: "btn btn-primary" %>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.collapse -->
  </div>
  <!-- /.card -->
  <div class="card">
    <div class="card-header" role="tab" id="photo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapsePhoto" aria-expanded="false" aria-controls="collapsePhoto">
          Create Photo
        </a>
      </h5>
      <!-- /.mb-0 -->
    </div>
    <!-- /.card-header -->
    <div id="collapsePhoto" class="collapse" role="tabpanel" aria-labelledby="photo" data-parent="#accordion">
      <div class="card-body">
        <%= form_for(@saint.saint_photos.build) do |f| %>
          <div><%= hidden_field_tag :current_saint_id, @saint.id %></div>
          <%= label_tag(:photo, "Upload Photo") %>
          <%= f.file_field :photo %>
          <%= label_tag(:photo_priority, "Photo Priority Level (Required)") %>
          <%= text_field_tag(:photo_priority) %>
          <%= label_tag(:photo_caption, "Write a Photo Caption") %>
          <%= text_field_tag(:photo_caption) %>
          <%= label_tag(:photo_description, "Write a Photo Description") %>
          <%= text_field_tag(:photo_description) %>
          <%= label_tag(:photo_alternative_text, "Write the alternative text for the photo") %>
          <%= text_field_tag(:photo_alternative_text) %>
          <%= label_tag(:width, "Width (Required)") %>
          <%= text_field_tag(:width) %>
          <%= label_tag(:height, "Height (Required)") %>
          <%= text_field_tag(:height) %>
          <%= f.submit "Create Photo", class: "btn btn-primary" %>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.collapse -->
  </div>
  <!-- /.card -->
  <div class="card">
    <div class="card-header" role="tab" id="writtenWork">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapseWrittenWork" aria-expanded="false" aria-controls="collapseWrittenWork">
          Create Written Work
        </a>
      </h5>
      <!-- /. mb-0 -->
    </div>
    <!-- /.card-header -->
    <div id="collapseWrittenWork" class="collapse" role="tabpanel" aria-labelledby="writtenWork" data-parent="#accordion">
      <div class="card-body">
        <%= form_for(@saint.written_works.build) do |f| %>
          <div><%= hidden_field_tag :current_saint_id, @saint.id %></div>
            <%= label_tag(:title, "Write the title of the written work:") %>
            <%= text_field_tag(:title) %>
            <%= label_tag(:publication_date, "Write publication date. (e.g. YYYY-MM-DD)") %>
            <%= text_field_tag(:publication_date) %>
            <%= label_tag(:publication_accuracy, "Write publication accuracy.") %>
            <%= text_field_tag(:publication_accuracy) %>
            <%= label_tag(:description, "Create optional description") %>
            <%= text_area_tag(:description) %>
            <%= f.submit "Create Written Work", class: "btn btn-primary" %>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.collapse -->
  </div>
  <!-- /.card -->
  <div class="card">
    <div class="card-header" role="tab" id="relatedSaint">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" href="#collapseRelatedSaint" aria-expanded="false" aria-controls="collapseRelatedSaint">
          Create Related Saint
        </a>
      </h5>
      <!-- /. mb-0 -->
    </div>
    <!-- /.card-header -->
    <div id="collapseRelatedSaint" class="collapse" role="tabpanel" aria-labelledby="relatedSaint" data-parent="#accordion">
      <div class="card-body">
        <%= form_for(@saint.active_relationships.build) do |f| %>
          <%= label_tag(:followed_id, "Write the id of the appropriate saint:") %>
          <%= text_field_tag(:followed_id) %>
          <%= label_tag(:status, "Explain this relationship:") %>
          <%= text_field_tag(:status) %>
          <div><%= hidden_field_tag :current_saint_id, @saint.id %></div>
          <%= f.submit "Create Relationship", class: "btn btn-primary" %>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.collapse -->
  </div>
  <!-- /.card -->
  <% if @timeline_events.any? %>
    <div class="card">
      <div class="card-header" role="tab" id="timelineEvents">
        <h5 class="mb-0">
          <a class="collapsed" data-toggle="collapse" href="#collapseTimelineEvents" aria-expanded="false" aria-controls="collapseTimelineEvents">
            Timeline Events
          </a>
        </h5>
        <!-- /. mb-0 -->
      </div>
      <!-- /.card-header -->
      <div id="collapseTimelineEvents" class="collapse" role="tabpanel" aria-labelledby="timelineEvents" data-parent="#accordion">
        <div class="card-body">
          <% @timeline_events.each do |timeline_event| %>
            <br>
            <b>
              Event Priority
            </b>
            <br>
            <%= timeline_event.event_priority %>
            <br>
            <b>
              Event Title
            </b>
            <br>
            <%= timeline_event.event_title %>
            <br>
            <b>
              Event Time
            </b>
            <br>
            <%= timeline_event.event_time %>
            <br>
            <b>
              Event Description
            </b>
            <br>
            <%= timeline_event.event_description %>
            <br>
            <%= image_tag timeline_event.image.url unless timeline_event.image.blank? %> 
            <br>
            <b>
              Image Caption
            </b>
            <br>
            <%= timeline_event.image_caption %>
            <br>
            <b>
              Image Description
            </b>
            <br>
            <%= timeline_event.image_description %>
            <br>
            <b>
              Image Alternative Text
            </b>
            <br>
            <%= timeline_event.image_alternative_text %>
            <br>
            <%= link_to "Edit Timeline Event", edit_timeline_event_path(timeline_event) %>
            <br>
          <% end %>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.collapse -->
    </div>
    <!-- /.card -->
  <% end %>
  <% if @saint_photos.any? %>
    <div class="card">
      <div class="card-header" role="tab" id="photos">
        <h5 class="mb-0">
          <a class="collapsed" data-toggle="collapse" href="#collapsePhotos" aria-expanded="false" aria-controls="collapsePhotos">
            Photos
          </a>
        </h5>
        <!-- /. mb-0 -->
      </div>
      <!-- /.card-header -->
      <div id="collapsePhotos" class="collapse" role="tabpanel" aria-labelledby="photos" data-parent="#accordion">
        <div class="card-body">
          <% @saint_photos.each do |saint_photo| %>
            <br>
            <%= image_tag saint_photo.photo.thumb.url unless saint_photo.photo.blank? %> 
            <br>
            <b>
              Photo Priority
            </b>
            <br>
            <%= saint_photo.photo_priority %>
            <br>
            <b>
              Caption:
            </b>
            <br>
            <%= saint_photo.photo_caption %>
            <br>
            <b>
              Description:
            </b>
            <br>
            <%= saint_photo.photo_description %>
            <br>
            <b>
              Alternative Text:
            </b>
            <br>
            <%= saint_photo.photo_alternative_text %>
            <br>
            <b>
              Width:
            </b>
            <br>
            <%= saint_photo.width %>
            <br>
            <b>
              Height:
            </b>
            <br>
            <%= saint_photo.height %>
            <br>
            <%= link_to "Edit Saint Photo", edit_saint_photo_path(saint_photo) %>
            <br>
            <%= link_to "Delete", saint_photo, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.collapse -->
    </div>
    <!-- /.card -->
  <% end %>
  <% if @written_works.any? %>
    <div class="card">
      <div class="card-header" role="tab" id="writtenWorks">
        <h5 class="mb-0">
          <a class="collapsed" data-toggle="collapse" href="#collapseWrittenWorks" aria-expanded="false" aria-controls="collapseWrittenWorks">
            Written Works
          </a>
        </h5>
        <!-- /. mb-0 -->
      </div>
      <!-- /.card-header -->
      <div id="collapseWrittenWorks" class="collapse" role="tabpanel" aria-labelledby="writtenWorks" data-parent="#accordion">
        <div class="card-body">
          <% @written_works.each do |written_work| %>
            <br>
            <%= written_work.title %> - 
            <% if written_work.publication_accuracy == 0 %>
              <%= written_work.publication_date.strftime("%-Y") %>
            <% elsif written_work.publication_accuracy == 1 %>
              <%= written_work.publication_date.strftime("%-Y") %>
            <% else %>
              <%= written_work.publication_date.strftime("%B %d, %-Y") %>
            <% end %>
            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_written_work_path(written_work) %> - 
              <%= link_to "Delete", written_work, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
            <% end %>
          <% end %>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.collapse -->
    </div>
    <!-- /.card -->
  <% end %>
  <% if @following_saints.any? %>
    <div class="card">
      <div class="card-header" role="tab" id="relatedSaints">
        <h5 class="mb-0">
          <a class="collapsed" data-toggle="collapse" href="#collapseRelatedSaints" aria-expanded="false" aria-controls="collapseRelatedSaints">
            Manage Relationships
          </a>
        </h5>
        <!-- /. mb-0 -->
      </div>
      <!-- /.card-header -->
      <div id="collapseRelatedSaints" class="collapse" role="tabpanel" aria-labelledby="relatedSaints" data-parent="#accordion">
        <div class="card-body">
          <% @saint.active_relationships.each do |relationship| %>
            Relationship: <%= relationship %>
            <br>
            Relationship ID: <%= relationship.id %>
            <br>
            Follower ID: <%= relationship.follower_id %>
            <br>
            Followed ID: <%= relationship.followed_id %>
            <br>
            Follower Saint Name: <%= Saint.find(relationship.follower_id).name %>
            <br>
            Status: <%= relationship.status %>
            <br>
            <% if relationship.id? %>
              <%= link_to 'Edit', edit_relationship_path(relationship) %>
              <br>
              <%= form_for(@saint.active_relationships.find_by(followed_id: relationship.followed_id), html: { method: :delete }) do |f| %>
                <div><%= hidden_field_tag :current_saint_id, @saint.id %></div>
                <%= f.submit "Destroy relationship", class: "btn" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.collapse -->
    </div>
    <!-- /.card -->
  <% end %>
</div>
<!-- /#accordion -->