config/routes.rb
Rails.application.routes.draw do
  resources :timeline_events
  get 'written_works/new'

  get 'saints/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'saints#map'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/signup',        to: 'users#new'
  post   '/signup',        to: 'users#create'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/map',           to: 'saints#map'
  get    '/pending_users', to: 'users#pending_users'
  
  resources :users do
    member do
      get 'approve_account'
      get 'deactivate_user'
      get 'reactivate_user'
      get 'promote_to_admin'
      get 'demote_to_user'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:     [:new, :create, :edit, :update]
  resources :saints do
    member do
      get :following, :followers
    end
  end
  resources :relationships
  resources :written_works
  resources :saint_photos
end

app/models/timeline_event.rb
class TimelineEvent < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :saint
  validates :saint_id, presence: true
  validates :event_priority, presence: true
  validates :event_title, presence: true
  validates :event_time, presence: true
  validates :event_description, presence: true
end

app/controllers/timeline_events_controller.rb
class TimelineEventsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    @timeline_events = TimelineEvent.all
  end

  def show
    @timeline_event = TimelineEvent.find(params[:id])
  end

  def new
    @timeline_event = TimelineEvent.new
  end

  def edit
    @timeline_event = TimelineEvent.find(params[:id])
  end

  def create
    current_saint = Saint.find(params[:current_saint_id])
    # current_saint.timeline_events.create(timeline_event_params)
    current_saint.timeline_events.create(event_priority: params[:event_priority],
                                         event_title: params[:event_title],
                                         event_time: params[:event_time],
                                         event_description: params[:event_description],
                                         image: params[:image],
                                         image_caption: params[:image_caption],
                                         image_description: params[:image_description],
                                         image_alternative_text: params[:image_alternative_text])
    redirect_to current_saint
  end

  def update
    @timeline_event = TimelineEvent.find(params[:id])
    respond_to do |format|
      if @timeline_event.update(timeline_event_params)
        format.html { redirect_to @timeline_event, notice: 'Timeline event was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeline_event }
      else
        format.html { render :edit }
        format.json { render json: @timeline_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @timeline_event.destroy
    respond_to do |format|
      format.html { redirect_to timeline_events_url, notice: 'Timeline event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def timeline_event_params
    params.require(:timeline_event).permit(:image, :image_caption, :image_description,
      :image_alternative_text, :event_description, :event_priority, :event_title,
      :event_time)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/timeline_events_helper.rb
module TimelineEventsHelper
end

app/views/timeline_events/_form.html.erb
<%= simple_form_for(@timeline_event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :saint_id %>
    <%= f.input :event_priority %>
    <%= f.input :event_title %>
    <%= f.input :event_time %>
    <%= f.input :image %>
    <%= f.input :image_caption %>
    <%= f.input :image_description %>
    <%= f.input :image_alternative_text %>
    <%= f.input :event_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/timeline_events/edit.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <h1>Editing Timeline Event</h1>
  
  <%= render 'form', timeline_event: @timeline_event %>
  
  <%= link_to 'Show', @timeline_event %> |
  <%= link_to 'Back', timeline_events_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/timeline_events/index.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <p id="notice"><%= notice %></p>
  <%= render 'shared/menu_toggle' %>

  <h1>Timeline Events</h1>
  
  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Image caption</th>
        <th>Image description</th>
        <th>Image alternative text</th>
        <th>Event description</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @timeline_events.each do |timeline_event| %>
        <tr>
          <td><%= timeline_event.image %></td>
          <td><%= timeline_event.image_caption %></td>
          <td><%= timeline_event.image_description %></td>
          <td><%= timeline_event.image_alternative_text %></td>
          <td><%= timeline_event.event_description %></td>
          <td><%= link_to 'Show', timeline_event %></td>
          <td><%= link_to 'Edit', edit_timeline_event_path(timeline_event) %></td>
          <td><%= link_to 'Destroy', timeline_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Timeline Event', new_timeline_event_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/timeline_events/new.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <h1>
    New Timeline Event
  </h1>
  
  <%= simple_form_for(@timeline_event) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :saint_id %>
      <%= f.input :event_priority %>
      <%= f.input :event_title %>
      <%= f.input :event_time %>
      <%= f.input :image %>
      <%= f.input :image_caption %>
      <%= f.input :image_description %>
      <%= f.input :image_alternative_text %>
      <%= f.input :event_description %>
    </div>
    <!-- /.form-inputs -->

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
    <!-- /.form-actions -->
  <% end %>
  
  <%= link_to 'Back', timeline_events_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>

app/views/timeline_events/show.html.erb
<%= render 'layouts/regular_sidebar' %>
<div id="page-content-wrapper">
  <%= render 'shared/menu_toggle' %>
  <p>
    <strong>Saint:</strong>
    <%= link_to @timeline_event.saint.name, @timeline_event.saint %>
  </p>
  
  <p>
    <strong>Event Priority:</strong>
    <%= @timeline_event.event_priority %>
  </p>
  
  <p>
    <strong>Event Title:</strong>
    <%= @timeline_event.event_title %>
  </p>
  
  <p>
    <strong>Event Description:</strong>
    <%= @timeline_event.event_description %>
  </p>
  
  <p>
    <strong>Event Time:</strong>
    <%= @timeline_event.event_time %>
  </p>
  
  <p>
    <strong>Image:</strong>
    <%= image_tag @timeline_event.image.url unless @timeline_event.image.blank? %> 
  </p>
  
  <p>
    <strong>Image caption:</strong>
    <%= @timeline_event.image_caption %>
  </p>
  
  <p>
    <strong>Image description:</strong>
    <%= @timeline_event.image_description %>
  </p>
  
  <p>
    <strong>Image alternative text:</strong>
    <%= @timeline_event.image_alternative_text %>
  </p>
  
  <p>
    <strong>Event description:</strong>
    <%= @timeline_event.event_description %>
  </p>
  
  <%= link_to 'Edit', edit_timeline_event_path(@timeline_event) %> |
  <%= link_to 'Back', timeline_events_path %>
</div>
<!-- /.page-content-wrapper -->
<%= render 'shared/top_of_page' %>
<%= render 'shared/side_menu_script' %>