config/routes.rb
Rails.application.routes.draw do
  resources :timeline_events
  get 'written_works/new'

  get 'saints/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'saints#map'
  get    '/help',          to: 'static_pages#help'
  get    '/about',         to: 'static_pages#about'
  get    '/signup',        to: 'users#new'
  post   '/signup',        to: 'users#create'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'
  get    '/map',           to: 'saints#map'
  get    '/pending_users', to: 'users#pending_users'
  
  resources :users do
    member do
      get 'approve_account'
      get 'deactivate_user'
      get 'reactivate_user'
      get 'promote_to_admin'
      get 'demote_to_user'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only:     [:new, :create, :edit, :update]
  resources :saints do
    member do
      get :following, :followers
    end
  end
  resources :relationships
  resources :written_works
  resources :saint_photos
end

app/views/layouts/_alerts.html.erb
<% flash.each do |message_type, message| %>
	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by Trevor Jin
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>

app/views/layouts/_regular_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        Saint Stories
      </a>
    </li>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "The Map", root_path %>
    </li>
    <li>
      <%= link_to "The Saints", saints_path %>
    </li>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <% if logged_in? %>
      <li>
        <%= link_to "Profile", current_user %>
      </li>
      <li>
        <%= link_to "Settings", edit_user_path(current_user) %>
      </li>
      <% if logged_in? && current_user.admin? %>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Pending Users", pending_users_path %>
        </li>
        <li>
          <%= link_to "Add Saint", new_saint_path %>
        </li>
        <li>
          <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>
<!-- /.sidebar-wrapper -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Saint Stories' %>
    <%= include_gon %>
    <%= render 'layouts/rails_default' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
    <%= render 'application/favicon' %>
  </head>
  <body>
    <div class="container" id="wrapper">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <!-- /.container -->
  </body>
</html>